{
 "title": "{dashboard_title}",
 "tags": [
  "network-slicing",
  "5g",
  "closed-loop"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Control Loop Iterations",
   "type": "gauge",
   "description": "Core Slice Simulation Iterations",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "slice_ambr_iteration", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Slice Demand",
   "type": "timeseries",
   "description": "Slice Demand",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "targets": [
    { "expr": "slice_ambr_demand", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Static AMBR slice assignment",
   "type": "timeseries",
   "description": "Static AMBR slice assignment",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    { "expr": "slice_ambr_static_bitrate", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Dynamic AMBR Reconfiguration per slice",
   "type": "timeseries",
   "description": "Dynamic AMBR Reconfiguration per slice",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    { "expr": "slice_ambr_dynamic_bitrate", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Acceptance Ratio (Static vs Dynamic)",
   "type": "timeseries",
   "description": "Total Acceptance Ratio (Static vs Dynamic)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "slice_ambr_acceptance_ratio_static*100",
     "legendFormat": "__auto"
    },
    {
     "expr": "slice_ambr_acceptance_ratio_dynamic*100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}